version: '3.8'
services:
  jenkins_agent_maven:
    image: jvalentino2/jenkins-agent-maven
    privileged: true
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_agent_maven
    volumes:
     - ./workspace:/home/jenkins/workspace
